---
title: "Writing functions"
author: "Jasmine Niu (jn2855)"
date: "2022-10-27"
output: github_document
---



```{r, include = FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(rvest)

set.seed(1) #the output on this page is fixed

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Let's write functionz


```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Suppose you want to do this often

```{r}
z_scores = function(x) { # x <- argument
  
  #Body of the function
  
  if(!is.numeric(x)) {
    stop("Z scores only work for numbers")

  }
  
  if(length(x) < 3) { #or else if
    stop("Z scores really only work if you have three or more numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  z #return(z)
  
}

z_scores(x_vec)
```



```{r}
z_scores(x = 1:10)
z_scores(x = rbinom(1000, 1, .6))

```


## Let's have multiple outputs

Let's just get the mean and sd form the vector input.

```{r}
mean_and_sd = function(x) {
  
  
  if(!is.numeric(x)) {
    stop("Z scores only work for numbers")

  }
  
  if(length(x) < 3) {
    stop("Z scores really only work if you have three or more numbers")
  }  
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}

mean_and_sd(x_vec)
mean_and_sd(x = 1:10)
mean_and_sd(x = rbinom(1000, 1, .6))
```


## Let's start with simulations...

```{r}
x_vec = rnorm(n = 25, mean = 17, sd =4)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```


Can I do this using a function...YUP

```{r}
sim_mean_sd = function(n_obs, true_mean = 7, true_sd = 4) {
  
  x_vec = rnorm(n = n_obs , mean = true_mean , sd = true_sd)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
  
}


```


does it work?

```{r}
sim_mean_sd(n_obs = 25000, true_mean = 10, true_sd = 4)

```


## Fixing bad stuff

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


Let's write a function to get reviews.

```{r}
read_page_reviews <- function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}

```



What good does this do?

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

dynamite_reviews
```


## Learning assessment

```{r}
lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) %>% 
    janitor::clean_names() %>% 
    gather(key = sex, value = words, female:male) %>% #~pivot_longer
    mutate(race = str_to_lower(race), movie = movie_name)
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "J3:L6", "return_king")
  ) %>% 
  select(movie, everything())
```


## Functions as argument

```{r}
x_vec = rnorm(25, 0, 1)

my_summary = function(x, summ_func) {
  summ_func(x)
}

my_summary(x_vec, sd)
my_summary(x_vec, IQR)
my_summary(x_vec, var)
```

## Scoping and names

```{r}
f = function(x) {
  z = x + y
  z
}

x = 1
y = 2

f(x = y) #x=2
```

